.class public final Lqz/y/q/b/v;
.super Lqz/u/c/m;
.source "SourceFile"

# interfaces
.implements Lqz/u/b/a;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lqz/u/c/m;",
        "Lqz/u/b/a<",
        "Lqz/y/q/b/u2/b/g;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic t:Lqz/y/q/b/b0$a;


# direct methods
.method public constructor <init>(Lqz/y/q/b/b0$a;)V
    .locals 0

    iput-object p1, p0, Lqz/y/q/b/v;->t:Lqz/y/q/b/b0$a;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lqz/u/c/m;-><init>(I)V

    return-void
.end method


# virtual methods
.method public invoke()Ljava/lang/Object;
    .locals 4

    .line 1
    iget-object v0, p0, Lqz/y/q/b/v;->t:Lqz/y/q/b/b0$a;

    iget-object v0, v0, Lqz/y/q/b/b0$a;->m:Lqz/y/q/b/b0;

    .line 2
    sget v1, Lqz/y/q/b/b0;->e:I

    .line 3
    invoke-virtual {v0}, Lqz/y/q/b/b0;->r()Lqz/y/q/b/u2/f/a;

    move-result-object v0

    .line 4
    iget-object v1, p0, Lqz/y/q/b/v;->t:Lqz/y/q/b/b0$a;

    iget-object v1, v1, Lqz/y/q/b/b0$a;->m:Lqz/y/q/b/b0;

    .line 5
    iget-object v1, v1, Lqz/y/q/b/b0;->c:Lqz/y/q/b/l2;

    .line 6
    invoke-virtual {v1}, Lqz/y/q/b/l2;->a()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lqz/y/q/b/b0$a;

    .line 7
    iget-object v1, v1, Lqz/y/q/b/f0;->a:Lqz/y/q/b/k2;

    sget-object v2, Lqz/y/q/b/f0;->c:[Lqz/y/k;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    .line 8
    invoke-virtual {v1}, Lqz/y/q/b/k2;->a()Ljava/lang/Object;

    move-result-object v1

    .line 9
    check-cast v1, Lqz/y/q/b/u2/b/z1/a/i;

    .line 10
    iget-boolean v2, v0, Lqz/y/q/b/u2/f/a;->c:Z

    if-eqz v2, :cond_0

    .line 11
    iget-object v1, v1, Lqz/y/q/b/u2/b/z1/a/i;->a:Lqz/y/q/b/u2/j/b/n;

    .line 12
    invoke-virtual {v1, v0}, Lqz/y/q/b/u2/j/b/n;->b(Lqz/y/q/b/u2/f/a;)Lqz/y/q/b/u2/b/g;

    move-result-object v0

    goto :goto_0

    .line 13
    :cond_0
    iget-object v1, v1, Lqz/y/q/b/u2/b/z1/a/i;->a:Lqz/y/q/b/u2/j/b/n;

    .line 14
    iget-object v1, v1, Lqz/y/q/b/u2/j/b/n;->c:Lqz/y/q/b/u2/b/y;

    .line 15
    invoke-static {v1, v0}, Lmz/h/i/s/a/l;->m0(Lqz/y/q/b/u2/b/y;Lqz/y/q/b/u2/f/a;)Lqz/y/q/b/u2/b/g;

    move-result-object v0

    :goto_0
    if-eqz v0, :cond_1

    return-object v0

    .line 16
    :cond_1
    iget-object v0, p0, Lqz/y/q/b/v;->t:Lqz/y/q/b/b0$a;

    iget-object v0, v0, Lqz/y/q/b/b0$a;->m:Lqz/y/q/b/b0;

    .line 17
    iget-object v1, v0, Lqz/y/q/b/b0;->d:Ljava/lang/Class;

    .line 18
    invoke-static {v1}, Lqz/y/q/b/u2/b/z1/a/e;->a(Ljava/lang/Class;)Lqz/y/q/b/u2/b/z1/a/e;

    move-result-object v1

    if-eqz v1, :cond_2

    .line 19
    iget-object v1, v1, Lqz/y/q/b/u2/b/z1/a/e;->b:Lqz/y/q/b/u2/d/b/o0/c;

    if-eqz v1, :cond_2

    .line 20
    iget-object v1, v1, Lqz/y/q/b/u2/d/b/o0/c;->a:Lqz/y/q/b/u2/d/b/o0/b;

    goto :goto_1

    :cond_2
    const/4 v1, 0x0

    :goto_1
    if-eqz v1, :cond_6

    .line 21
    invoke-virtual {v1}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    if-eqz v2, :cond_5

    const/4 v1, 0x1

    if-eq v2, v1, :cond_6

    const/4 v1, 0x2

    if-eq v2, v1, :cond_4

    const/4 v1, 0x3

    if-eq v2, v1, :cond_3

    const/4 v1, 0x4

    if-eq v2, v1, :cond_4

    const/4 v1, 0x5

    if-eq v2, v1, :cond_4

    .line 22
    new-instance v0, Lkotlin/NoWhenBranchMatchedException;

    invoke-direct {v0}, Lkotlin/NoWhenBranchMatchedException;-><init>()V

    throw v0

    .line 23
    :cond_3
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection "

    const-string v3, "library has no idea what declarations does it have. Please use Java reflection to inspect this class: "

    .line 24
    invoke-static {v2, v3}, Lmz/b/b/a/a;->n0(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 25
    iget-object v0, v0, Lqz/y/q/b/b0;->d:Ljava/lang/Class;

    .line 26
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 27
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 28
    :cond_4
    new-instance v1, Ljava/lang/UnsupportedOperationException;

    const-string v2, "Packages and file facades are not yet supported in Kotlin reflection. "

    const-string v3, "Meanwhile please use Java reflection to inspect this class: "

    .line 29
    invoke-static {v2, v3}, Lmz/b/b/a/a;->n0(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 30
    iget-object v0, v0, Lqz/y/q/b/b0;->d:Ljava/lang/Class;

    .line 31
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 32
    invoke-direct {v1, v0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v1

    .line 33
    :cond_5
    new-instance v2, Lqz/y/q/b/i2;

    const-string v3, "Unknown class: "

    invoke-static {v3}, Lmz/b/b/a/a;->h0(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v3

    .line 34
    iget-object v0, v0, Lqz/y/q/b/b0;->d:Ljava/lang/Class;

    .line 35
    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string v0, " (kind = "

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v3, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 v0, 0x29

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v2, v0}, Lqz/y/q/b/i2;-><init>(Ljava/lang/String;)V

    throw v2

    .line 36
    :cond_6
    new-instance v1, Lqz/y/q/b/i2;

    const-string v2, "Unresolved class: "

    invoke-static {v2}, Lmz/b/b/a/a;->h0(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    .line 37
    iget-object v0, v0, Lqz/y/q/b/b0;->d:Ljava/lang/Class;

    .line 38
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    invoke-direct {v1, v0}, Lqz/y/q/b/i2;-><init>(Ljava/lang/String;)V

    throw v1
.end method
